name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
softdepend: [Citizens]
commands:
  Built:
    aliases: [/built]
    description: Displays Built Help
    usage: /Built